cmake_minimum_required(VERSION 4.1)
project(Tareaprogramacion2)

set(CMAKE_CXX_STANDARD 20)

add_executable(Tareaprogramacion2 main.cpp
        ejercicio1.cpp
        ejercicio2.cpp
        ejercicio3.cpp
        ejercicio4.cpp
        ejercicio5.cpp
        ejercicio6.cpp
        ejercicio7.cpp
        ejercicio8.cpp
        ejercicio9.cpp
        ejercicio10.cpp
        ejercicio11.cpp
        ejercicio12.cpp
        "ejercicio puntos extra.cpp")
